  POST http://localhost:3001/tasks
  Content-Type: application/json
  
  {   
    "title":"Title of the Task",
    "dueDate":"2026-01-27T08:12:00.000Z",
    "description":"Description of the Task Description of the Task Description of the Task Description of the Task Description of the Task Description of the Task",
    "priority":"normal",
    "status":"todo"
  }