GET http://localhost:3001/some.text
GET http://localhost:3001/posts
GET http://localhost:3001/post
GET http://localhost:3001/tagname
GET http://localhost:3001/tagline
GET http://localhost:3001/error/404
GET http://localhost:3001/error/403
GET http://localhost:3001/superfly
GET http://localhost:3001/butterfly
GET http://localhost:3001/star
GET http://localhost:3001/rockstar
GET http://localhost:3001/starfish